<?php

namespace Aoceu\ToyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinRepository extends EntityRepository
{
}
